### PR TITLE
vote: proposing EXONER4TED as maintainer

### PR DESCRIPTION
**Pull request by EXONER4TED**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

/kind documentation

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area crawler

> /area ci

> /area utils

**What this PR does / why we need it**:

Proposing @EXONER4TED as maintainer as discussed with @FedeDP 

I would love to help maintain this project!

**Which issue(s) this PR fixes**:

Fixes # N/A

**Special notes for your reviewer**:

I'm really appreciative to be a part of such cool projects here in the Falco community 😄

### CODE REVIEW

**Comment by FedeDP** [comment]
/hold to host the vote!
Of course, for me, big :+1: !
@EXONER4TED helped a lot with fixes, improvements and new distros support, i am really glad that he is taking the next step :)

**Comment by maxgio92** [comment]
+1

**Comment by leogr** [comment]
Big +1 from me! :partying_face:

**Comment by zuc** [comment]
+1! 🚀

**Comment by FedeDP** [comment]
We reached majority! @EXONER4TED can you add yourself to the kernel-crawler members on test-infra: https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml#L559 ?

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by EXONER4TED** [comment]
Opened this PR! https://github.com/falcosecurity/test-infra/pull/1076

**Pull request merged**
