### PR TITLE
new: update-kernels workflow on kernels branch

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area ci

**What this PR does / why we need it**:

Duplicated the `update-kernels` workflow from main branch to `kernels` one.
Moreover, allow the `update-kernels` job to close and reopen the PR it creates, to trigger the CI workflow run.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
This is a wip because i am playing around trying to understand whether this is feasible!

**Review by leogr — APPROVED** [review]

**Pull request merged**
