### PR TITLE
fix(kernel_crawler): fixed opensuse tumbleweed crawler.

### LINKED ISSUE #133: OpenSUSE tumbleweed not crawled
**Describe the bug**

It seems like we are not crawling http://download.opensuse.org/tumbleweed/repo/oss/x86_64/

**How to reproduce it**

Check that no `kernel-default-devel` present in there is present in the output json of kernel-crawler.

**Expected behaviour**

We should be able to crawl it!

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area crawler

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #133

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
I discovered more repos and added them.
/cc @maxgio92 @EXONER4TED

**Comment by FedeDP** [comment]
Results:
From this branch (x86 kernels.json artifact generated by PR ci):
```
grep "opensuse\"" kernels.json | wc -l
19
```

From master (x86):
```
grep "opensuse\"" list.json | wc -l
11
```

**Review by maxgio92 — APPROVED** [review]
LGTM, thanks @FedeDP 

/approve

**Pull request merged**
