### PR TITLE
fix(kernel_crawler): properly support debian `cloud` and `rt` flavors.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area crawler

**What this PR does / why we need it**:

Do not mixup headers, otherwise we might end up building a module for the wrong flavor, and it won't load.

See https://github.com/falcosecurity/falco/issues/2625 for the issue.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
New output (cut):
```
python -m kernel_crawler.main crawl --distro Debian
Scanning http://mirrors.edge.kernel.org/debian/  [####################################]  100%
Scanning http://security.debian.org/  [####################################]  100%                    org/
Checking repositories  [####################################]  100%
Listing packages  [####################################]  100%
Building dependency tree  [####################################]  100%
{
  "Debian": [
    {
      "kernelversion": 1,
      "kernelrelease": "6.1.27-1-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.1.0-9-amd64_6.1.27-1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.1.0-9-common_6.1.27-1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-6.1_6.1.27-1_amd64.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "6.1.27-1-rt-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.1.0-9-rt-amd64_6.1.27-1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.1.0-9-common-rt_6.1.27-1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-6.1_6.1.27-1_amd64.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "6.1.27-1-cloud-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.1.0-9-cloud-amd64_6.1.27-1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.1.0-9-common_6.1.27-1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-6.1_6.1.27-1_amd64.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "5.18.16-1~bpo11+1-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.18.0-0.deb11.4-common_5.18.16-1~bpo11+1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-5.18_5.18.16-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.18.0-0.deb11.4-amd64_5.18.16-1~bpo11+1_amd64.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "5.18.16-1~bpo11+1-rt-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-5.18_5.18.16-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.18.0-0.deb11.4-common-rt_5.18.16-1~bpo11+1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.18.0-0.deb11.4-rt-amd64_5.18.16-1~bpo11+1_amd64.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "5.18.16-1~bpo11+1-cloud-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.18.0-0.deb11.4-common_5.18.16-1~bpo11+1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-5.18_5.18.16-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.18.0-0.deb11.4-cloud-amd64_5.18.16-1~bpo11+1_amd64.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "5.19.11-1~bpo11+1-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-5.19_5.19.11-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.19.0-0.deb11.2-common_5.19.11-1~bpo11+1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.19.0-0.deb11.2-amd64_5.19.11-1~bpo11+1_amd64.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "5.19.11-1~bpo11+1-rt-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.19.0-0.deb11.2-rt-amd64_5.19.11-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-5.19_5.19.11-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.19.0-0.deb11.2-common-rt_5.19.11-1~bpo11+1_all.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "5.19.11-1~bpo11+1-cloud-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-5.19_5.19.11-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.19.0-0.deb11.2-common_5.19.11-1~bpo11+1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-5.19.0-0.deb11.2-cloud-amd64_5.19.11-1~bpo11+1_amd64.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "6.0.3-1~bpo11+1-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-6.0_6.0.12-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.2-amd64_6.0.3-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.2-common_6.0.3-1~bpo11+1_all.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "6.0.3-1~bpo11+1-rt-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.2-rt-amd64_6.0.3-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-6.0_6.0.12-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.2-common-rt_6.0.3-1~bpo11+1_all.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "6.0.3-1~bpo11+1-cloud-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.2-cloud-amd64_6.0.3-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-6.0_6.0.12-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.2-common_6.0.3-1~bpo11+1_all.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "6.0.12-1~bpo11+1-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.6-common_6.0.12-1~bpo11+1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-6.0_6.0.12-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.6-amd64_6.0.12-1~bpo11+1_amd64.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "6.0.12-1~bpo11+1-rt-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.6-common-rt_6.0.12-1~bpo11+1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.6-rt-amd64_6.0.12-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-6.0_6.0.12-1~bpo11+1_amd64.deb"
      ]
    },
    {
      "kernelversion": 1,
      "kernelrelease": "6.0.12-1~bpo11+1-cloud-amd64",
      "target": "debian",
      "headers": [
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.6-common_6.0.12-1~bpo11+1_all.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-kbuild-6.0_6.0.12-1~bpo11+1_amd64.deb",
        "http://mirrors.edge.kernel.org/debian/pool/main/l/linux/linux-headers-6.0.0-0.deb11.6-cloud-amd64_6.0.12-1~bpo11+1_amd64.deb"
      ]
    },
   ...
```

Note how we have new `-rt` and `-cloud` flavors now.
Note: [falco-driver-loader](https://github.com/falcosecurity/falco/blob/master/scripts/falco-driver-loader) support for `rt` and `cloud` is out of scope for now.

**Comment by FedeDP** [comment]
/unhold 
User reported that the kmod built with correct headers is working fine: https://github.com/falcosecurity/falco/issues/2625#issuecomment-1583039915

**Comment by EXONER4TED** [comment]
This all looks good to me! Sorry for taking so long to look into this. We had handled this internally with a kludge solution to split them out after the fact. I will be extremely pleased to remove that and have it properly in place now 👍 

Sorry for not contributing the fix upstream earlier, I had thought kernel-crawler was working as intended hahaha...

**Review by EXONER4TED — APPROVED** [review]
Gotta love Debian for having 3 urls required per kernel 😜

**Pull request merged**
