### PR TITLE
new: last run distro

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

Added a last run distro file that will be downloaded and parsed by our test-infra automation, to allow dbg to only update relevant (ie: changed) distros.
Can be either "*" or a distro name. It is filled automatically by update-kernels CI (main branch).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
See #150 and https://github.com/falcosecurity/test-infra/pull/1178

**Review by cappellinsamuele — APPROVED** [review]

**Review by maxgio92 — APPROVED** [review]
/approve

**Comment by maxgio92** [comment]
Thanks @FedeDP. I think it's good enough and the goal is to speed up and make the pipeline to DBG agile.

**Pull request merged**
