### PR TITLE
Introduce support to AlmaLinux and RockyLinux

### PR DESCRIPTION
**Pull request by dark-vex**
Signed-off-by: Daniele De Lorenzi <daniele.delorenzi@fastnetserv.net>

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area crawler

**What this PR does / why we need it**:
This PR introduce the possibility to crawl AlmaLinux and RockyLinux kernel packages

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
That's neat! Thank you very much!
/approve

**Comment by FedeDP** [comment]
@dark-vex Are you willing to also open the  PR on [driverkit](https://github.com/falcosecurity/driverkit) to support AlmaLinux (Rocky is already supported)? Thank you!

**Comment by dark-vex** [comment]
@FedeDP My knowledge on golang is very poor but I can give a shot! :)

**Comment by FedeDP** [comment]
<3 Yay! Should be pretty simple because we already have rocky in there! 
Thank you!

**Pull request merged**
