### PR TITLE
chore(ci): dropped github action because we will now use a prow job.

### PR DESCRIPTION
**Pull request by FedeDP**
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind documentation

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area crawler

/area ci

> /area utils

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

I'd wait for this weekend PR created by prow before merging this, to be sure to avoid any breakage.

### CODE REVIEW

**Comment by FedeDP** [comment]
/unhold
@leogr @maxgio92

**Comment by maxgio92** [comment]
@FedeDP is this still a WIP?

**Comment by FedeDP** [comment]
Nice catch eheh

@maxgio92 it is not :)

**Review by leogr — APPROVED** [review]

**Pull request merged**
