### PR TITLE
new(ci): add github test ci for main.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area ci

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
The ci is a bit slow :rofl:

**Comment by FedeDP** [comment]
/unhold
This is ready.

**Review by maxgio92 — APPROVED** [review]
/approve

**Pull request merged**
