### PR TITLE
new: docker image

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area crawler

/area ci

**What this PR does / why we need it**:

The PR adds a docker image to be used by clients; moreover, it fixes a bit the python packages, and allows `pip3 install .` to install a py script that runs `kernel_crawer.main.cli`, ie: the main program entrypoint.

The docker image is only built when merging in main.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
I am not 100% sure about the circleci config; it should work though :/ 
@leogr can you take a look?

**Comment by FedeDP** [comment]
Testing the workflow on my branch: https://app.circleci.com/pipelines/github/FedeDP/kernel-crawler

**Comment by FedeDP** [comment]
It worked! https://hub.docker.com/repository/docker/fededp/kernel-crawler :D 

```
docker run -ti --rm fededp/kernel-crawler crawl --help
Usage: kernel-crawler crawl [OPTIONS]

Options:
    --distro [AmazonLinux|AmazonLinux2|AmazonLinux2022|CentOS|Debian|Fedora|Flatcar|Minikube|Oracle6|Oracle7|Oracle8|PhotonOS|Redhat|Ubuntu|*]
    --version TEXT
    --arch [x86_64|aarch64]
    --out_fmt [plain|json|driverkit]
    --image TEXT                    Option is required when distro is Redhat.
    --help                          Show this message and exit.
```

removing wip :)

**Review by leogr — APPROVED** [review]

**Pull request merged**
