### PR TITLE
fix(ci): fixed `if:` condition for update-kernels single distro update step

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area ci

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
This should fix the update-kernels ci :)

**Review by leogr — APPROVED** [review]

**Comment by FedeDP** [comment]
tide :sleeping:

**Comment by leogr** [comment]
Closing and reopening to trigger the CI

**Comment by FedeDP** [comment]
Nope, it is tide that is receiving 401 from github :)

**Comment by leogr** [comment]
Note: I'm exceptionally merging this using GH UI since @poiana is temporarily not working.
We need this soon to start processing new drivers.

**Pull request merged**
