### PR TITLE
fix(ci): use a dev version of `create-pull-request` action to fix issue.

### LINKED ISSUE #1170: `fatal: --local can only be used inside a git repository` error on containers
### Subject of the issue

Maybe related to actions/checkout#760.

This action seems to fail on containers using the latest version of Git.
The checkout action had a fix for this yesterday, but I believe other actions like this one continue to be affected.

### Steps to reproduce

Use this action on containers like `ubuntu:focal`.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area ci

**What this PR does / why we need it**:

Uses dev version of `create-pull-request` action to fix https://github.com/peter-evans/create-pull-request/issues/1170

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
~~Wip because i moved `update-kernels` on pull request trigger to be able to quickly test it.~~

**Comment by FedeDP** [comment]
The PR was created! https://github.com/falcosecurity/kernel-crawler/pull/93
:smiley: 
Removing wip.

**Comment by FedeDP** [comment]
I still don't get why on #93 the CI job is not being triggered :/ 

EDIT: because of: https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536204092

**Comment by FedeDP** [comment]
/unhold

I will move the `update-kernels` workflow to the `kernels` branch in a subsequent PR; then, the `test kernel-crawler` job will be triggered by:
```
on:
  workflow_run:
    workflows: [update-kernels]
    types:
      - completed
```
And will then checkout the `update/kernels` branch to perform the `jq` validation step.

**Review by leogr — APPROVED** [review]

**Pull request merged**
