### PR TITLE
adjust rockylinux driverkit target to rocky

### PR DESCRIPTION
**Pull request by EXONER4TED**
Signed-off-by: Logan Bond <lbond@secureworks.com>

**What type of PR is this?**
Adjusting the `rockylinux` target for driverkit to just `rocky` - which is what driverkit expects.

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind documentation

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area crawler

> /area ci

> /area utils

**What this PR does / why we need it**:
Adjust the driverkit target output from `rockylinux` -> `rocky`
Output from driverkit:
```
  -t, --target string             the system to target the build for, one of [almalinux,amazonlinux,amazonlinux2,amazonlinux2022,arch,centos,debian,fedora,flatcar,minikube,photon,redhat,rocky,ubuntu,vanilla]
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by FedeDP — COMMENTED** [review]
Mmmh the rule here is to use the OS_ID from /etc/os-release!
Are we sure "rocky" is the correct one? Otherwise we should fix driverkit instead IMHO :)

**Comment by EXONER4TED** [comment]
Here's a screenshot from a Rocky 9 VM I spun up a moment ago - looks like they show it as just `rocky`.

image

**Comment by FedeDP** [comment]
Yay thank you very much!

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
