### PR TITLE
fix(kernel_crawler): enforce kernelversion to be a string.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area crawler

**What this PR does / why we need it**:

Part 2 of #165 :D 
I forgot a couple of occurrences of int `kernelversion`.
Moreover, i also added a type check when building the `repo.DriverkitConfig` object.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by maxgio92 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
The error is unrelated from this PR:
>   File "/home/runner/.local/lib/python3.10/site-packages/kernel_crawler/utils/download.py", line 26, in get_url
    return zlib.decompress(resp.content, 47)
zlib.error: Error -3 while decompressing data: incorrect header check 

and it's working just fine locally.

**Pull request merged**
